# This workflow tests the project on all platforms.

# For more information see: 
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test Runner

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-15 # macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4 # latest-stable

      - name: Tests All Platforms
        run: bash scripts/test.sh